name: db
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  json_annotation: ^4.8.1
  orm: ^3.4.8
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.0
